---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: default

---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: dummyrepo-config
  namespace: default
data:
  NODE_ENV: production
  PORT: "3000"

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummyrepo-deployment
  namespace: default
  labels:
    app: dummyrepo
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: dummyrepo
      tier: backend
  template:
    metadata:
      labels:
        app: dummyrepo
        tier: backend
        version: v1
    spec:
      containers:
      - name: dummyrepo-app
        image: DOCKER_USERNAME/dummyrepo-mcp-hackathon:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: dummyrepo-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: dummyrepo-config
              key: PORT
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
# Service - ClusterIP (for internal communication)
apiVersion: v1
kind: Service
metadata:
  name: dummyrepo-service
  namespace: default
  labels:
    app: dummyrepo
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: dummyrepo
    tier: backend
  sessionAffinity: None

---
# Service - NodePort (for external access)
apiVersion: v1
kind: Service
metadata:
  name: dummyrepo-nodeport-service
  namespace: default
  labels:
    app: dummyrepo
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30000
    name: http
  selector:
    app: dummyrepo
    tier: backend

---
# Horizontal Pod Autoscaler (Optional - for scaling based on CPU/Memory)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dummyrepo-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dummyrepo-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max

---
# PodDisruptionBudget (for maintaining availability during disruptions)
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dummyrepo-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: dummyrepo
      tier: backend
